version: '3.8'
networks:
  ocr-network:
    driver: bridge

services:
  # --- DATABASE LAYER ---
  db:
    image: ankane/pgvector:latest # Postgres 16 + pgvector
    container_name: ocr_gateway_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ocr_gateway
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ocr_gateway"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ocr-network

  # --- MESSAGE BROKER ---
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ocr_gateway_mq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    networks:
      - ocr-network

  # --- CACHE & DEDUPLICATION ---
  redis:
    image: redis:7-alpine
    container_name: ocr_gateway_redis
    ports:
      - "6379:6379"
    networks:
      - ocr-network

  # --- OBSERVABILITY (LANGFUSE) ---
  langfuse-db:
    image: postgres:16
    container_name: langfuse_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse -d langfuse"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: ${LANGFUSE_DB_PASSWORD}
      POSTGRES_DB: langfuse
    volumes:
      - langfuse_pgdata:/var/lib/postgresql/data
    networks:
      - ocr-network

  langfuse:
    image: langfuse/langfuse:2
    container_name: langfuse_server
    depends_on:
      langfuse-db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://langfuse:${LANGFUSE_DB_PASSWORD}@langfuse-db:5432/langfuse
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET_KEY}
      - SALT=${my_salt}
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=false # Нам нужен закрытый контур
    networks:
      - ocr-network

  minio:
    image: minio/minio
    container_name: ocr-minio
    ports:
      - "9000:9000"       # API
      - "9001:9001"       # Console UI
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - ocr-network

volumes:
  pgdata:
  rabbitdata:
  langfuse_pgdata:
  minio_data:
