spring:
  application:
    name: ocr-gateway
  # --- PostgreSQL Configuration ---
  datasource:
    url: jdbc:postgresql://localhost:5432/ocr_gateway
    username: admin
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Или validate, none, create
    show-sql: true
    properties:
      hibernate.format_sql: true

  # --- RabbitMQ Configuration ---
  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        concurrency: 2
        max-concurrency: 5
        prefetch: 1
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

  # --- Redis Configuration ---
  data:
    redis:
      host: localhost
      port: 6379
      # Пароль в композе не задан, эту строку можно оставить пустой или удалить
      # password: your_redis_password
  # Лимит на один файл (ставим 50 Мб)
  servlet:
    multipart:
      max-file-size: 50MB
  # Лимит на весь запрос целиком
      max-request-size: 50MB

app:
  minio:
    endpoint: http://localhost:9005
    external-url: ${MINIO_EXTERNAL_URL:http://localhost:9005}
    access-key: admin
    secret-key: ${MINIO_ROOT_PASSWORD}
    bucket-raw: ocr-artifacts
    bucket-proc: ocr-processed
    expiry-min: 15
  rabbitmq:
    exchange: ocr.exchange
    routing-key: ocr.key
    queues:
      incoming: ocr.tasks.queue
      results: ocr.results.queue
  langfuse:
    host: http://localhost:3000
    public-key: ${LANGFUSE_PK}
    secret-key: ${LANGFUSE_SK}
  upload:
    max-size: 20MB
#    allowed-types: application/pdf,image/jpeg,image/png
    allowed-types: application/pdf
# --- Actuator/Healthcheck Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics"
  endpoint:
    health:
      show-details: "always"
#logging:
#  level:
#    com.langfuse: DEBUG
#    org.apache.http: DEBUG
#    okhttp3: DEBUG